version: '1.0'

services:
  app:
    image: '9970ea2c8210dc1db1e1e64e07782af09061e01caa5695c69a3f8481f10dd525'
    container_name: app_demo_rest
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_User=postgr
      - DB_PASSWORD=password
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgr
      - POSTGRES_PASSWORD=password





